name: CI

on:
  release:
    types: [published]

  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up V version latest
        uses: nocturlab/setup-vlang-action@master
        with:
          v-version: latest

      - name: Build executable
        run: |
          mkdir out
          v -o out/KodularStarter KodularStarter.v

      - name: Set executable bit
        if: matrix.os != 'windows-latest'
        run: chmod +x ./out/KodularStarter

      - id: dl-rcedit
        name: Download rcedit
        if: matrix.os == 'windows-latest'
        uses: carlosperate/download-file-action@v1.0.3
        with:
            file-url: 'https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe'

      - name: Set icon to exe
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          "${{ steps.dl-rcedit.outputs.file-path }}" "out/KodularStarter.exe" --set-icon icon.ico --set-file-version 2 --set-product-version 2 --set-version-string "ProductName" "Kodular Starter"

      - uses: actions/upload-artifact@v2
        with:
          name: KodularStarter_${{ matrix.os }}
          path: out/*

      - name: Zip release
        if: github.event_name == 'release'
        run: zip -r KodularStarter_${{ matrix.os }}.zip out

      - name: Get release
        id: get_release
        if: github.event_name == 'release'
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload release binary
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./KodularStarter_${{ matrix.os }}.zip
          asset_name: KodularStarter_${{ matrix.os }}.zip
          asset_content_type: application/zip
