name: CI

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up V version latest
        uses: nocturlab/setup-vlang-action@master
        with:
          v-version: latest

      - name: Build executable
        run: |
          mkdir out
          v -prod -o out/KodularStarter KodularStarter.v

      - name: Set executable bit
        if: matrix.os != 'windows-latest'
        run: chmod +x ./out/KodularStarter

      - name: Set metadata to exe
        if: matrix.os == 'windows-latest'
        run: ./ext/rcedit-x64.exe out/KodularStarter.exe --set-icon icon.ico --set-file-version 2 --set-product-version 2 --set-version-string "ProductName" "Kodular Starter"

      - uses: actions/upload-artifact@v2
        with:
          name: KodularStarter_${{ runner.os == 'Windows' && 'Windows.exe' || runner.os }}
          path: out/*
          
  release:
    name: Create GitHub release
    needs: build
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/v')

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    
    steps:
      - name: Get short tag name
        uses: jungwinter/split@v1
        id: split
        with:
          msg: ${{ github.ref }}
          seperator: /

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.split.outputs._2 }}
          draft: true
          prerelease: false

  publish:
    name: Publish 
    needs: release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [Linux, Windows, macOS]    

    steps:
      - uses: actions/checkout@v2

      - name: Fetch artifacts
        uses: actions/download-artifact@v1
        with:
          name: KodularStarter_${{ matrix.os == 'Windows' && 'Windows.exe' || matrix.os }}
          path: ./${{ matrix.os }}

      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./${{ matrix.os }}/KodularStarter_${{ matrix.os == 'Windows' && 'Windows.exe' || matrix.os }}
          asset_name: KodularStarter_${{ matrix.os == 'Windows' && 'Windows.exe' || matrix.os }}
          asset_content_type: application/octet-stream
